version: "3.9"

services:
  app:
    build: .
    container_name: creatorlink-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - DATABASE_URL=postgres://user:password@db:5432/appdb
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - db
    command: npm run dev  # nodemon 실행용

  db:
    image: postgres:15
    container_name: creatorlink-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
